In [1]:
import pandas as pd

In [19]:

# File to Load (Remember to Change These)
matches_to_load = "Resources/matches_250.csv"
players_to_load = "Resources/ranked_players.csv"

#read in pandas
read_matches_csv = pd.read_csv(matches_to_load)
read_players_csv = pd.read_csv(players_to_load)

In [20]:
read_players_csv

,Unnamed: 0,Name,Nat,Pts,Tournaments,Link,Nickname
0,0,Djokovic Novak,Serbia,"12,030",18,https://www.tennis24.com/player/djokovic-novak...,Djokovic N. (Srb)
1,1,Nadal Rafael,Spain,"9,850",18,https://www.tennis24.com/player/nadal-rafael/x...,Nadal R. (Esp)
2,2,Medvedev Daniil,Russia,"9,735",24,https://www.tennis24.com/player/medvedev-danii...,Medvedev D. (Rus)
3,3,Thiem Dominic,Austria,"9,125",21,https://www.tennis24.com/player/thiem-dominic/...,Thiem D. (Aut)
4,4,Federer Roger,Switzerland,"6,630",16,https://www.tennis24.com/player/federer-roger/...,Federer R. (Sui)
...,...,...,...,...,...,...,...
2024,2024,Frost Linus,Sweden,1,11,https://www.tennis24.com/player/frost-linus/dM...,NaN
2025,2025,Marrero Curbelo Ivan,Spain,1,11,https://www.tennis24.com/player/marrero-curbel...,NaN
2026,2026,Trocker Moritz,Italy,1,13,https://www.tennis24.com/player/trocker-moritz...,NaN
2027,2027,Akkoyun Umut,Turkey,1,14,https://www.tennis24.com/player/akkoyun-umut/6...,NaN
2028,2028,Boureau Alexis,France,1,14,https://www.tennis24.com/player/boureau-alexis...,NaN

In [22]:
clean_csv = read_matches_csv.drop('Unnamed: 0', axis =1)
clean_csv.tail()

,Date,P1,P2,Result,Score,Set1,Set2,Set3,Set4,Set5,Court_Type,Tournament
6441,30/09/2020,Moriya H. (Jpn),Leite W. (Bra),1.0,2-0,6-2,6-1,NaN,NaN,NaN,hard,ITF MEN - SINGLES: M25 Porto (Portugal)
6442,14/09/2020,Cretu C. (Rou),Moriya H. (Jpn),1.0,2-1,2-6,6-3,6-4,NaN,NaN,clay,CHALLENGER MEN - SINGLES: Iasi (Romania)
6443,24/02/2020,Moriya H. (Jpn),Molcan A. (Svk),-1.0,1-2,2-6,7-6,4-6,NaN,NaN,hard (indoor),CHALLENGER MEN - SINGLES: Pau (France)
6444,28/01/2020,Moriya H. (Jpn),Zverev M. (Ger),-1.0,0-2,2-6,6-7,NaN,NaN,NaN,hard (indoor),CHALLENGER MEN - SINGLES: Quimper (France)
6445,15/01/2020,Moriya H. (Jpn),Rubin N. (Usa),1.0,2-0,7-6,7-5,NaN,NaN,NaN,hard,ATP - SINGLES: Australian Open (Australia) - Q...