In [1]:
# Dependencies

import pandas as pd
from config import cloudM, cloudMpassword
import requests
import pymongo
import pandas as pd
from pymongo import MongoClient

In [2]:
#in this notenook I will extract the table of the most recent champions from each major tennis tournament 

us_open_url = 'https://en.wikipedia.org/wiki/US_Open_(tennis)'
us_open_table = pd.read_html(us_open_url)
us_open_table

[                                                0  \
 0                                             NaN
 1                                Official website
 2                                         Founded
 3                                        Editions
 4                                        Location
 5                                           Venue
 6                                         Surface
 7                                     Prize money
 8                                           Men's
 9                                            Draw
 10                              Current champions
 11                            Most singles titles
 12                            Most doubles titles
 13                                        Women's
 14                                           Draw
 15                              Current champions
 16                            Most singles titles
 17                            Most doubles titles
 18                                  Mixed doubles
 19                                           Draw
 20                              Current champions
 21                             Most titles (male)
 22                           Most titles (female)
 23                                     Grand Slam
 24  Australian Open French Open Wimbledon US Open
 25                                 Last completed
 26                                   2020 US Open

                                                     1
 0                                                 NaN
 1                                    Official website
 2                                 1881; 140 years ago
 3                                          140 (2020)
 4               New York City, New York,United States
 5   USTA Billie Jean King National Tennis Center (...
 6   Grass – outdoors (1881–1974)Clay – outdoors (1...
 7                           US$53.4 million (2020)[1]
 8                                               Men's
 9                                   128S / 128Q / 64D
 10  Dominic Thiem (singles)Mate PavićBruno Soares ...
 11           7 Richard SearsWilliam LarnedBill Tilden
 12              6Mike BryanRichard SearsHolcombe Ward
 13                                            Women's
 14                                  128S / 128Q / 64D
 15  Naomi Osaka (singles)Laura SiegemundVera Zvona...
 16                                     8Molla Mallory
 17                          13Margaret Osborne duPont
 18                                      Mixed doubles
 19                                                 32
 20                  Bethanie Mattek-SandsJamie Murray
 21                 4 Bill TildenBill TalbertBob Bryan
 22                          9 Margaret Osborne duPont
 23                                         Grand Slam
 24      Australian Open French Open Wimbledon US Open
 25                                     Last completed
 26                                       2020 US Open  ,
    2020    2019    2018    2017    2016    2015    2014    2013    2012  \
 0  0[d]  737872  732663  691143  688542  691280  713642  713026  710803

      2011    2010    2009    2008    2007    2006    2005
 0  658664  712976  721059  720227  715587  640000  659538  ,
                0        1        2       3          4          5          6   \
 0           Event        W        F      SF  4th Round  3rd Round  2nd Round
 1         Singles  3800000  1850000  925000     475000     266000     156000
 2        Doubles*   700000   350000  166400      85275        NaN      27876
 3  Mixed Doubles*   155000    70000   30000      15000      10000       5000

           7      8      9      10      11
 0  1st Round     Q3     Q2     Q1     NaN
 1      93000  54000  30000  16000  8000.0
 2      16500    NaN    NaN    NaN     NaN
 3        NaN    NaN    NaN    NaN     NaN  ,
          0          1     2     3    4    5    6    7   8   9
 0    Event      Event     W     F   SF   QF   4R   3R  2R  1R
 1  Singles        Men  2000  1200  720  360  180   90  45  10
 2  Singles  Women[61]  2000  1300  780  430  240  130  70  10
 3  Doubles        Men  2000  1200  720  360  180   90   0   –
 4  Doubles      Women  2000  1300  780  430  240  130  10   –,
                    Event                            Champion  \
 0    Men's singles final                       Dominic Thiem
 1  Women's singles final                         Naomi Osaka
 2    Men's doubles final             Mate Pavić Bruno Soares
 3  Women's doubles final      Laura Siegemund Vera Zvonareva
 4    Mixed doubles final  Bethanie Mattek-Sands Jamie Murray

                       Runner-up                         Score
 0              Alexander Zverev  2–6, 4–6, 6–4, 6–3, 7–6(8–6)
 1             Victoria Azarenka                 1–6, 6–3, 6–3
 2  Wesley Koolhof Nikola Mektić                      7–5, 6–3
 3      Nicole Melichar Xu Yifan                      6–4, 6–4
 4  Chan Hao-ching Michael Venus                      6–2, 6–3  ,
                                                Record               Era  \
 0                                      Men since 1881    Men since 1881
 1                           Most men's singles titles       Before 1968
 2                           Most men's singles titles       Before 1968
 3                           Most men's singles titles       Before 1968
 4                           Most men's singles titles          Open Era
 5                           Most men's singles titles          Open Era
 6                           Most men's singles titles          Open Era
 7                Most consecutivemen's singles titles       Before 1968
 8                Most consecutivemen's singles titles          Open Era
 9                           Most men's doubles titles       Before 1968
 10                          Most men's doubles titles       Before 1968
 11                          Most men's doubles titles          Open Era
 12               Most consecutivemen's doubles titles       Before 1968
 13               Most consecutivemen's doubles titles          Open Era
 14               Most consecutivemen's doubles titles          Open Era
 15                  Men with mostmixed doubles titles          All time
 16                  Men with mostmixed doubles titles          All time
 17                  Men with mostmixed doubles titles          All time
 18                  Men with mostmixed doubles titles          All time
 19                  Men with mostmixed doubles titles          All time
 20                  Men with mostmixed doubles titles          All time
 21                  Men with mostmixed doubles titles          All time
 22  Most titles (singles,men's doubles,mixed doubl...       Before 1968
 23  Most titles (singles,men's doubles,mixed doubl...          Open Era
 24                                   Women since 1887  Women since 1887
 25                        Most women's singles titles       Before 1968
 26                        Most women's singles titles          Open Era
 27                        Most women's singles titles          Open Era
 28             Most consecutive women'ssingles titles       Before 1968
 29             Most consecutive women'ssingles titles       Before 1968
 30             Most consecutive women'ssingles titles          Open Era
 31                         Most women'sdoubles titles       Before 1968
 32                         Most women'sdoubles titles          Open Era
 33             Most consecutive women'sdoubles titles       Before 1968
 34             Most consecutive women'sdoubles titles          Open Era
 35             Most consecutive women'sdoubles titles          Open Era
 36                Women with mostmixed doubles titles       Before 1968
 37                Women with mostmixed doubles titles          Open Era
 38                Women with mostmixed doubles titles          Open Era
 39                Women with mostmixed doubles titles          Open Era
 40  Most titles (singles,women's doubles, mixed do...       Before 1968
 41  Most titles (singles,women's doubles, mixed do...          Open Era
 42                                      Miscellaneous     Miscellaneous
 43                            Youngest singles titles               Men
 44                            Youngest singles titles             Women
 45                              Oldest singles titles               Men
 46                              Oldest singles titles             Women
 47                                         Match wins               Men
 48                                         Match wins             Women

                   Player(s)                      Count  \
 0            Men since 1881             Men since 1881
 1             Richard Sears                          7
 2            William Larned                          7
 3               Bill Tilden                          7
 4             Jimmy Connors                          5
 5              Pete Sampras                          5
 6             Roger Federer                          5
 7             Richard Sears                          7
 8             Roger Federer                          5
 9             Richard Sears                          6
 10            Holcombe Ward                          6
 11               Mike Bryan                          6
 12            Richard Sears                          6
 13          Todd Woodbridge                          2
 14           Mark Woodforde                          2
 15         Edwin P. Fischer                          4
 16       Wallace F. Johnson                          4
 17              Bill Tilden                          4
 18             Bill Talbert                          4
 19            Owen Davidson                          4
 20            Marty Riessen                          4
 21                Bob Bryan                          4
 22              Bill Tilden                         16
 23                Bob Bryan                          9
 24         Women since 1887           Women since 1887
 25          / Molla Mallory                          8
 26              Chris Evert                          6
 27          Serena Williams                          6
 28          / Molla Mallory                          4
 29             Helen Jacobs                          4
 30              Chris Evert                          4
 31  Margaret Osborne duPont                         13
 32      Martina Navratilova                          9
 33  Margaret Osborne duPont                         10
 34   Virginia Ruano Pascual                          3
 35             Paola Suárez                          3
 36  Margaret Osborne duPont                          9
 37           Margaret Court                          3
 38         Billie Jean King                          3
 39      Martina Navratilova                          3
 40  Margaret Osborne duPont                         25
 41      Martina Navratilova                         16
 42            Miscellaneous              Miscellaneous
 43             Pete Sampras   19 years and 1 month[62]
 44             Tracy Austin  16 years and 8 months[62]
 45           William Larned  38 years and 8 months[62]
 46          / Molla Mallory  42 years and 5 months[62]
 47            Jimmy Connors             98 (1970-1992)
 48          Serena Williams            106 (1998-2020)

                                                 Years
 0                                      Men since 1881
 1                                             1881–87
 2                                    1901–02, 1907–11
 3                                       1920–25, 1929
 4                           1974, 1976, 1978, 1982–83
 5                           1990, 1993, 1995–96, 2002
 6                                             2004–08
 7                                             1881–87
 8                                             2004–08
 9   1882–84, 1886–87 with James Dwight1885 with Jo...
 10  1899–1901 with Dwight F. Davis1904–06 with Bea...
 11  2005, 2008, 2010, 2012, 2014 with Bob Bryan201...
 12                                            1882–87
 13                                            1995–96
 14                                            1995–96
 15  1894–96 with Juliette Atkinson1898 with Carrie...
 16  1907 with May Sayers1909, 1911, 1915 with Haze...
 17  1913–14 with Mary Browne1922–23 with Molla Mal...
 18               1943–46 with Margaret Osborne duPont
 19  1966 with Donna Floyd1967, 1971, 1973 with Bil...
 20  1969–70, 1972 with Margaret Court1980 with Wen...
 21  2003 with Katarina Srebotnik2004 with Vera Zvo...
 22  1913–29 (7 singles,5 men's doubles,4 mixed dou...
 23          2003–14 (5 men's doubles,4 mixed doubles)
 24                                   Women since 1887
 25                             1915–18, 1920–22, 1926
 26                                1975–78, 1980, 1982
 27                          1999, 2002, 2008, 2012–14
 28                                            1915–18
 29                                            1932–35
 30                                            1975–78
 31  1941 with Sarah Palfrey Cooke1942–50, 1955–57 ...
 32  1977 with Betty Stöve1978, 1980 with Billie Je...
 33  1941 with Sarah Palfrey Cooke1942–50 with Loui...
 34                                            2002–04
 35                                            2002–04
 36  1943–46 with Bill Talbert1950 with Ken McGrego...
 37                   1969–70, 1972 with Marty Riessen
 38   1971, 1973 with Owen Davidson1976 with Phil Dent
 39  1985 with Heinz Günthardt1987 with Emilio Sánc...
 40  1941–60 (3 singles,13 women's doubles,9 mixed ...
 41  1977–2006 (4 singles,9 women's doubles,3 mixed...
 42                                      Miscellaneous
 43                           19 years and 1 month[62]
 44                          16 years and 8 months[62]
 45                          38 years and 8 months[62]
 46                          42 years and 5 months[62]
 47                                     98 (1970-1992)
 48                                    106 (1998-2020)  ,
                       0                                      1  \
 0  Preceded byWimbledon  Grand Slam TournamentAugust–September
 1  Preceded byNew Haven           US Open SeriesJuly–September

                              2
 0  Succeeded byAustralian Open
 1             Succeeded byNone  ,
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteUS Open  \
 0  Men's singles Women's singles Men's doubles Wo...
 1                                       Pre Open Era
 2                                           Open Era
 3                                 Open-era finalists

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteUS Open.1
 0  Men's singles Women's singles Men's doubles Wo...
 1  1881 1882 1883 1884 1885 1886 1887 1888 1889 1...
 2  1968 1969 1970 1971 1972 1973 1974 1975 1976 1...
 3                                 Open-era finalists                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ,
       Articles and topics related to US Open (tennis)  \
 0   vteUS Open men's singles drawsheetsPre Open Er...
 1                 vteUS Open men's singles drawsheets
 2                                        Pre Open Era
 3                                            Open Era
 4                 vteUS Open men's doubles drawsheets
 5                                        Pre Open Era
 6                                            Open Era
 7               vteUS Open women's singles drawsheets
 8                                        Pre Open Era
 9                                            Open Era
 10              vteUS Open women's doubles drawsheets
 11                                       Pre Open Era
 12                                           Open Era
 13                        vteMajor tennis tournaments
 14                                         Grand Slam
 15                                             Former
 16                                          vteTennis
 17  History Glossary Match types Statistics Player...
 18                                             Basics
 19                                            General
 20                                             Courts
 21                                              Shots
 22                                        Grand Slams
 23                                             Events
 24                                              Stats
 25                                  Professionaltours
 26                                                Men
 27                                              Women
 28                             Team tennistournaments
 29                                             Active
 30                                            Defunct
 31                                  Multi-sportevents
 32                                   Intercontinental
 33                                        Continental
 34                                   Governing bodies
 35                Tennis portal  Outline  WikiCommons
 36                 vteGrand Slam tournament champions
 37                         Grand Slam overall records
 38                                    Australian Open
 39                                        French Open
 40                                          Wimbledon

In [3]:
#extract the correct table
us_df = us_open_table[4]
us_df

,Event,Champion,Runner-up,Score
0,Men's singles final,Dominic Thiem,Alexander Zverev,"2–6, 4–6, 6–4, 6–3, 7–6(8–6)"
1,Women's singles final,Naomi Osaka,Victoria Azarenka,"1–6, 6–3, 6–3"
2,Men's doubles final,Mate Pavić Bruno Soares,Wesley Koolhof Nikola Mektić,"7–5, 6–3"
3,Women's doubles final,Laura Siegemund Vera Zvonareva,Nicole Melichar Xu Yifan,"6–4, 6–4"
4,Mixed doubles final,Bethanie Mattek-Sands Jamie Murray,Chan Hao-ching Michael Venus,"6–2, 6–3"

In [4]:
#add new column for tournament name distinguising later in Mongo 
tourn_name = ['US Open', 'US Open', 'US Open', 'US Open', 'US Open']

us_df["Tournament"] = tourn_name
us_df

,Event,Champion,Runner-up,Score,Tournament
0,Men's singles final,Dominic Thiem,Alexander Zverev,"2–6, 4–6, 6–4, 6–3, 7–6(8–6)",US Open
1,Women's singles final,Naomi Osaka,Victoria Azarenka,"1–6, 6–3, 6–3",US Open
2,Men's doubles final,Mate Pavić Bruno Soares,Wesley Koolhof Nikola Mektić,"7–5, 6–3",US Open
3,Women's doubles final,Laura Siegemund Vera Zvonareva,Nicole Melichar Xu Yifan,"6–4, 6–4",US Open
4,Mixed doubles final,Bethanie Mattek-Sands Jamie Murray,Chan Hao-ching Michael Venus,"6–2, 6–3",US Open

In [5]:
aus_open_url = 'https://en.wikipedia.org/wiki/Australian_Open'
aus_open_table = pd.read_html(aus_open_url)

In [6]:
aus_df = aus_open_table[3]
aus_df

,Event,Champion,Runner-up,Score
0,Men's Singles,Novak Djokovic,Daniil Medvedev,"7–5, 6–2, 6–2"
1,Women's Singles,Naomi Osaka,Jennifer Brady,"6–4, 6–3"
2,Men's Doubles,Ivan Dodig Filip Polášek,Rajeev Ram Joe Salisbury,"6–3, 6–4"
3,Women's Doubles,Elise Mertens Aryna Sabalenka,Barbora Krejčíková Kateřina Siniaková,"6–2, 6–3"
4,Mixed Doubles,Barbora Krejčíková Rajeev Ram,Samantha Stosur Matthew Ebden,"6–1, 6–4"

In [7]:
tourn_name = ['Aus Open', 'Aus Open', 'Aus Open', 'Aus Open','Aus Open' ]
aus_df["Tournament"] = tourn_name
aus_df

,Event,Champion,Runner-up,Score,Tournament
0,Men's Singles,Novak Djokovic,Daniil Medvedev,"7–5, 6–2, 6–2",Aus Open
1,Women's Singles,Naomi Osaka,Jennifer Brady,"6–4, 6–3",Aus Open
2,Men's Doubles,Ivan Dodig Filip Polášek,Rajeev Ram Joe Salisbury,"6–3, 6–4",Aus Open
3,Women's Doubles,Elise Mertens Aryna Sabalenka,Barbora Krejčíková Kateřina Siniaková,"6–2, 6–3",Aus Open
4,Mixed Doubles,Barbora Krejčíková Rajeev Ram,Samantha Stosur Matthew Ebden,"6–1, 6–4",Aus Open

In [8]:
french_open_url = 'https://en.wikipedia.org/wiki/French_Open'
french_open_table = pd.read_html(french_open_url)

In [9]:
french_df = french_open_table[2]
french_df

,Event,Champion,Runner-up,Score
0,Men's Singles,Rafael Nadal,Novak Djokovic,"6–0, 6–2, 7–5"
1,Women's Singles,Iga Świątek,Sofia Kenin,"6–4, 6–1"
2,Men's Doubles,Kevin Krawietz Andreas Mies,Mate Pavić Bruno Soares,"6–3, 7–5"
3,Women's Doubles,Tímea Babos Kristina Mladenovic,Alexa Guarachi Desirae Krawczyk,"6–4, 7–5"
4,Mixed Doubles,Latisha Chan Ivan Dodig,Gabriela Dabrowski Mate Pavić,"6–1, 7–6(7–5)"

In [10]:
tourn_name = ['French Open', 'French Open', 'French Open','French Open','French Open']
french_df['Tournament'] = tourn_name
french_df

,Event,Champion,Runner-up,Score,Tournament
0,Men's Singles,Rafael Nadal,Novak Djokovic,"6–0, 6–2, 7–5",French Open
1,Women's Singles,Iga Świątek,Sofia Kenin,"6–4, 6–1",French Open
2,Men's Doubles,Kevin Krawietz Andreas Mies,Mate Pavić Bruno Soares,"6–3, 7–5",French Open
3,Women's Doubles,Tímea Babos Kristina Mladenovic,Alexa Guarachi Desirae Krawczyk,"6–4, 7–5",French Open
4,Mixed Doubles,Latisha Chan Ivan Dodig,Gabriela Dabrowski Mate Pavić,"6–1, 7–6(7–5)",French Open

In [11]:
wim_open_url = 'https://en.wikipedia.org/wiki/The_Championships,_Wimbledon'
wim_open_table = pd.read_html(wim_open_url)

In [12]:
wim_df = wim_open_table[3]
wim_df

,Event,Champion,Runner-up,Score
0,Gentlemen's Singles,Novak Djokovic,Roger Federer,"7–6(7–5), 1–6, 7–6(7–4), 4–6, 13–12(7–3)"
1,Ladies' Singles,Simona Halep,Serena Williams,"6–2, 6–2"
2,Gentlemen's Doubles,Juan Sebastián Cabal Robert Farah,Nicolas Mahut Édouard Roger-Vasselin,"6–7(5–7), 7–6(7–5), 7–6(8–6), 6–7(5–7), 6–3"
3,Ladies' Doubles,Barbora Strýcová Su-Wei Hsieh,Gabriela Dabrowski Xu Yifan,"6–2, 6–4"
4,Mixed Doubles,Latisha Chan Ivan Dodig,Jeļena Ostapenko Robert Lindstedt,"6–2, 6–3"

In [13]:
tourn_name = ['Wimbledon','Wimbledon', 'Wimbledon', 'Wimbledon', 'Wimbledon' ]
wim_df['Tournament'] = tourn_name
wim_df

,Event,Champion,Runner-up,Score,Tournament
0,Gentlemen's Singles,Novak Djokovic,Roger Federer,"7–6(7–5), 1–6, 7–6(7–4), 4–6, 13–12(7–3)",Wimbledon
1,Ladies' Singles,Simona Halep,Serena Williams,"6–2, 6–2",Wimbledon
2,Gentlemen's Doubles,Juan Sebastián Cabal Robert Farah,Nicolas Mahut Édouard Roger-Vasselin,"6–7(5–7), 7–6(7–5), 7–6(8–6), 6–7(5–7), 6–3",Wimbledon
3,Ladies' Doubles,Barbora Strýcová Su-Wei Hsieh,Gabriela Dabrowski Xu Yifan,"6–2, 6–4",Wimbledon
4,Mixed Doubles,Latisha Chan Ivan Dodig,Jeļena Ostapenko Robert Lindstedt,"6–2, 6–3",Wimbledon

In [14]:
mongodb+srv://sbakshi908:<password>@summyamongo.afc2i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

SyntaxError: invalid syntax (<ipython-input-14-1998952abc8b>, line 1)

In [15]:
#make the mongo connection
client = MongoClient()
#method 1 local
#client = MongoClient('localhost', 27017)


#cloud_string = 'mongodb+srv://'+cloudM+':'+cloudMpassword+'@summyamongo.afc2i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
#method 2 cloud 
cloud_str = f"mongodb+srv://sbakshi908:{cloudMpassword}@summyamongo.afc2i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
client = MongoClient(cloud_str)

In [16]:
print(cloud_string)

NameError: name 'cloud_string' is not defined

In [17]:
# Declare the database
db = client.ETLdb

# Declare the collection
coll = db.tourn_champs
coll.drop()

In [19]:
#iterate through each row in df (we will have to do this 4 times)
for index, row in us_df.iterrows():
    print (row)
    coll.insert_one(row.to_dict())

Event                  Men's singles final
Champion                     Dominic Thiem
Runner-up                 Alexander Zverev
Score         2–6, 4–6, 6–4, 6–3, 7–6(8–6)
Tournament                         US Open
Name: 0, dtype: object
Event         Women's singles final
Champion                Naomi Osaka
Runner-up         Victoria Azarenka
Score                 1–6, 6–3, 6–3
Tournament                  US Open
Name: 1, dtype: object
Event                  Men's doubles final
Champion           Mate Pavić Bruno Soares
Runner-up     Wesley Koolhof Nikola Mektić
Score                             7–5, 6–3
Tournament                         US Open
Name: 2, dtype: object
Event                  Women's doubles final
Champion      Laura Siegemund Vera Zvonareva
Runner-up           Nicole Melichar Xu Yifan
Score                               6–4, 6–4
Tournament                           US Open
Name: 3, dtype: object
Event                        Mixed doubles final
Champion      Bethanie Mattek-Sands Jamie Murray
Runner-up           Chan Hao-ching Michael Venus
Score                                   6–2, 6–3
Tournament                               US Open
Name: 4, dtype: object

In [20]:
#create a variable for the dictionary that will be inserted into the collection
us_open_dict = us_df.to_dict('records')

In [21]:
#insert to collection
coll.insert_many(us_open_dict)

### Next the Australian Open

In [22]:
#iterate through each row in df (we will have to do this 4 times)
for index, row in aus_df.iterrows():
    print (row)
    coll.insert_one(row.to_dict())

Event           Men's Singles
Champion       Novak Djokovic
Runner-up     Daniil Medvedev
Score           7–5, 6–2, 6–2
Tournament           Aus Open
Name: 0, dtype: object
Event         Women's Singles
Champion          Naomi Osaka
Runner-up      Jennifer Brady
Score                6–4, 6–3
Tournament           Aus Open
Name: 1, dtype: object
Event                    Men's Doubles
Champion      Ivan Dodig Filip Polášek
Runner-up     Rajeev Ram Joe Salisbury
Score                         6–3, 6–4
Tournament                    Aus Open
Name: 2, dtype: object
Event                               Women's Doubles
Champion              Elise Mertens Aryna Sabalenka
Runner-up     Barbora Krejčíková Kateřina Siniaková
Score                                      6–2, 6–3
Tournament                                 Aus Open
Name: 3, dtype: object
Event                         Mixed Doubles
Champion      Barbora Krejčíková Rajeev Ram
Runner-up     Samantha Stosur Matthew Ebden
Score                              6–1, 6–4
Tournament                         Aus Open
Name: 4, dtype: object

In [23]:
#create a variable for the dictionary that will be inserted into the collection
aus_open_dict = aus_df.to_dict('records')

In [24]:
#insert to collection
coll.insert_many(aus_open_dict)

### Now French Open

In [25]:
#iterate through each row in df (we will have to do this 4 times)
for index, row in french_df.iterrows():
    print (row)
    coll.insert_one(row.to_dict())

Event          Men's Singles
Champion        Rafael Nadal
Runner-up     Novak Djokovic
Score          6–0, 6–2, 7–5
Tournament       French Open
Name: 0, dtype: object
Event         Women's Singles
Champion          Iga Świątek
Runner-up         Sofia Kenin
Score                6–4, 6–1
Tournament        French Open
Name: 1, dtype: object
Event                       Men's Doubles
Champion      Kevin Krawietz Andreas Mies
Runner-up         Mate Pavić Bruno Soares
Score                            6–3, 7–5
Tournament                    French Open
Name: 2, dtype: object
Event                         Women's Doubles
Champion      Tímea Babos Kristina Mladenovic
Runner-up     Alexa Guarachi Desirae Krawczyk
Score                                6–4, 7–5
Tournament                        French Open
Name: 3, dtype: object
Event                         Mixed Doubles
Champion            Latisha Chan Ivan Dodig
Runner-up     Gabriela Dabrowski Mate Pavić
Score                         6–1, 7–6(7–5)
Tournament                      French Open
Name: 4, dtype: object

In [26]:
#create a variable for the dictionary that will be inserted into the collection
french_open_dict = french_df.to_dict('records')

In [27]:
#insert to collection
coll.insert_many(french_open_dict)

### Last Wimbledon

In [28]:
#iterate through each row in df (we will have to do this 4 times)
for index, row in wim_df.iterrows():
    print (row)
    coll.insert_one(row.to_dict())

Event                              Gentlemen's Singles
Champion                                Novak Djokovic
Runner-up                                Roger Federer
Score         7–6(7–5), 1–6, 7–6(7–4), 4–6, 13–12(7–3)
Tournament                                   Wimbledon
Name: 0, dtype: object
Event         Ladies' Singles
Champion         Simona Halep
Runner-up     Serena Williams
Score                6–2, 6–2
Tournament          Wimbledon
Name: 1, dtype: object
Event                                 Gentlemen's Doubles
Champion                Juan Sebastián Cabal Robert Farah
Runner-up            Nicolas Mahut Édouard Roger-Vasselin
Score         6–7(5–7), 7–6(7–5), 7–6(8–6), 6–7(5–7), 6–3
Tournament                                      Wimbledon
Name: 2, dtype: object
Event                       Ladies' Doubles
Champion      Barbora Strýcová Su-Wei Hsieh
Runner-up       Gabriela Dabrowski Xu Yifan
Score                              6–2, 6–4
Tournament                        Wimbledon
Name: 3, dtype: object
Event                             Mixed Doubles
Champion                Latisha Chan Ivan Dodig
Runner-up     Jeļena Ostapenko Robert Lindstedt
Score                                  6–2, 6–3
Tournament                            Wimbledon
Name: 4, dtype: object

In [29]:
#create a variable for the dictionary that will be inserted into the collection
wim_open_dict = wim_df.to_dict('records')

In [30]:
#insert to collection
coll.insert_many(wim_open_dict)